#!/bin/sh

mkdir -p /entrypoint/start-scripts

/entrypoint/start-scripts/start-*

crond -c /config/cron/crontabs -L /logs/crond/crond.log -b -l 8 && supervisord --nodaemon --configuration /etc/supervisord.conf