#!/bin/sh

mkdir -p /entrypoint/start-scripts

for entrypoint in /entrypoint/start-scripts/start-*; do
    chmod +x "$entrypoint"
    "$entrypoint"
done

crond -c /config/cron/crontabs -L /logs/crond/crond.log -b -l 8 && supervisord --nodaemon --configuration /etc/supervisord.conf